[package]
org= "ballerina"
name= "openapi"
version= "1.4.2"

[[platform.java11.dependency]]
path = "../openapi-validator/build/libs/openapi-validator-1.4.2-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "1.4.2-SNAPSHOT"
