[plugin]
id = "openapi-tools"
class = "io.ballerina.openapi.validator.OpenAPIValidatorPlugin"

[[dependency]]
path = "../openapi-validator/build/libs/openapi-validator-2.0.1-@project.version@"
groupId = "ballerina"
artifactId = "openapi"
version = "@project.version@"
